### PR TITLE
Add Ruby VM metrics dashboard and visualisations

### PR DESCRIPTION
**Pull request by mikker**
@axw: Is this how to do it?
@bmorelli25: Added you as the readme is (almost?) docs. I copied the one from the Node.js agent.

image

### CODE REVIEW

**Comment by mikker** [comment]
Done. Those hourly jobs look fun!

**Comment by axw** [comment]
> Done. Those hourly jobs look fun!

Are you using TSVB? I'd just clamp the values to > 0 by using the "positive_only" parent pipeline aggregation of the derivative.

**Comment by mikker** [comment]
_TSVB?_

I think the negatives are right after a deploy/restart of the process. I'll add positive_only 👍 thanks Andrew!

**Comment by mikker** [comment]
_Time Series Visual Builder_ is my guess. Where do I find the option?

**Comment by mikker** [comment]
Found it.

**Pull request merged**
