### PR TITLE
fix: update nodejs dashboards to work with 7.10

### PR DESCRIPTION
**Pull request by astorm**
The intent of this PR is to update the Node.js Dashboards such that, after importing, 

1. The dashboards will be populated with data
2. Already defined index pattern objects will be left intact

This PR accomplishes this by 

1. Ensuring that every visualization has their `index_pattern` field set to `apm-*`.  Modern versions of Kibana appear to interpret an empty value as a literal empty string, and will not fallback to the default index pattern.  This means after importing charts are empty.

2. Removing the `apm-*` index pattern as an importable object

Re: _Removing the `apm-*` index pattern as an importable object_ 

Elastic Cloud includes an `apm-*` pattern by default AND the default behavior of the importer is to _replace_ objects.  This means that the existing import file can stomp on a user's existing index pattern and add fields that may be out of date for their Kibana version. This is fixable via a refresh, but is unexpected and may confusing the user if their `apm-*` pattern stops working. 

Additionally -- it appears that when a TSVB visualizations ask for an `index_pattern`, they're not looking for a _defined_ index pattern.  Instead it's a literal pattern of indexes to match.  In other words, so long as we set the `index_pattern` in each visualization to `apm-*`, the data source for the TSVB charts will work, even if there's no `apm-*` defined at `Stack Management -> Kibana -> Index Patterns`

The above's making a number of assumptions -- in addition to standard code review trying to import these dashboards into an elastic instance that's monitoring a node application would be appropriate.

### CODE REVIEW

**Comment by trentm** [comment]
nit: Please include this update:

```
--- a/apm-agent-nodejs/dashboards/readme.md
+++ b/apm-agent-nodejs/dashboards/readme.md
@@ -5,7 +5,7 @@ This is a collection of dashboards, visualizations, and searches that you can us

 ### Installation

-Dashboards are imported on the **Management > Saved objects** page.
+Dashboards are imported on the **Stack Management > Saved objects** page.
```

or something like it.

**Comment by astorm** [comment]
```
-Dashboards are imported on the **Management > Saved objects** page.
+Dashboards are imported on the **Stack Management > Saved objects** page.
```

Good call, and done.

**Comment by trentm** [comment]
Nit: "Support for JSON files is going away

Use our updated export to generate NDJSON files, and you'll be all set."

Should we re-export this to ndjson format to use for the update?

Screen Shot 2020-11-23 at 4 24 13 PM

**Comment by trentm** [comment]
nit:

Screen Shot 2020-11-23 at 4 26 32 PM

Is this "Lucene" format here because https://github.com/elastic/apm-contrib/blob/master/apm-agent-nodejs/dashboards/nodejs-runtime-metrics-7.x.json#L14 vs.

```
 "searchSourceJSON": "{\"query\":{\"language\":\"kuery\",\"query\":\"\"},...
```

from the [java](https://github.com/elastic/apm-contrib/blob/master/apm-agent-java/dashboards/java_metrics_dashboard_7.x.json) and go dashboards?

**Review by trentm — APPROVED** [review]
I added a couple more nits, but it WFM:

Screen Shot 2020-11-23 at 4 35 09 PM

so I'm fine if we push those nits to subsequent changes.

**Review by vigneshshanmugam — APPROVED** [review]
👍 lgtm

**Comment by astorm** [comment]
> Should we re-export this to ndjson format to use for the update?

Good question -- sticking with the older JSON format was a deliberate choice and I figure we'll revisit  the `ndjson` format if/when plain json support is dropped.  That said  it's worth revisiting my thinking here -- if only to discover what other people know :) 

I don't know the history of when `ndjson` files were introduced as the import/export format so I'm unsure how far back in the 7.x branch they're supported ([this thread hints at the default changing in 7.2](https://discuss.elastic.co/t/saved-items-import-export-json-ndjson-discrepancy/199834)).  I'm also unsure how dramatically (if at all) the export format changed during the lifetime of the 7.x branch. My concern about picking the ndjson format is that it won't be as well supported across multiple versions of the platform.

The older JSON format seems like it has a better chance of being supported on older versions of the platform as well as current versions.  My approach here was to make as small of a change as possible to the dashboard file to get things working with 7.10.  By keeping the change small I hoped to reduce that chance that things will be broken in the older 7.x version.

I'll own that this is more intuition based than hard science based -- but for 1. a contrib module where 2. the community can open Issues or PRs if they run into trouble and 3. The failure state is "your dashboards aren't imported" it still seems like the right trade-off to make -- especially w/r/t time.

**Comment by astorm** [comment]
> Is this "Lucene" format here because https://github.com/elastic/apm-contrib/blob/master/apm-agent-nodejs/dashboards/nodejs-runtime-metrics-7.x.json#L14 vs.

Seems like it.  I did some quick export tests and `lucene` and `kuery` do seem to be the keywords that control which search type is chosen by default.  I don't have strong opinions on what the default should be, but I'm going to err on the side of leaving this as lucene for now. If folks want/need KQL it's just a click away.

**Comment by watson** [comment]
Regarding ndjson: Support for regular json will not be removed in `7.x`, so it's safe to keep using this for the `7.x` dashboard

**Pull request merged**
